#!/usr/bin/env python3
"""Generates assets/search-index.js for the ⌘K command palette.

The index ships as a script that assigns window.SITE_SEARCH_INDEX rather than as
JSON, so search also works on pages opened straight from disk, where a browser
refuses to fetch() a file:// URL.

Crawls the real pages instead of keeping a hand-written list, so the palette
cannot drift out of sync with the site:

  - blog posts     title + location/date meta + a snippet of the opening
  - standalone pages (home, gallery)
  - gallery photos  location caption + camera settings from the built markup

Run after adding a post or photo:

    python3 tools/build_search_index.py
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "assets", "search-index.js")

BANNER = "/* Generated by tools/build_search_index.py. Do not edit by hand. */\n"

PAGES = [
    {
        "title": "Home",
        "url": "index.html",
        "group": "Pages",
        "meta": "terminal · type help",
        "keywords": "home cd ~ terminal shell command line landing",
    },
    {
        "title": "Adventure Blogs",
        "url": "blogs/blogs.html",
        "group": "Pages",
        "meta": "all trip reports",
        "keywords": "blog blogs adventures index posts hiking skiing",
    },
    {
        "title": "Photography",
        "url": "photography/portfolio.html",
        "group": "Pages",
        "meta": "gallery",
        "keywords": "photography photos gallery portfolio camera",
    },
]


def text_of(html):
    """Strips tags and collapses whitespace."""
    plain = re.sub(r"<(script|style)\b.*?</\1>", " ", html, flags=re.S | re.I)
    plain = re.sub(r"<[^>]+>", " ", plain)
    plain = (
        plain.replace("&amp;", "&")
        .replace("&nbsp;", " ")
        .replace("&mdash;", "—")
        .replace("&#8212;", "—")
        .replace("&quot;", '"')
        .replace("&lt;", "<")
        .replace("&gt;", ">")
    )
    return re.sub(r"\s+", " ", plain).strip()


def first(pattern, html, group=1):
    match = re.search(pattern, html, re.S)
    return text_of(match.group(group)) if match else ""


# Captions use compact labels ("Yellow Stone NP, WY"). Expand them so a
# visitor typing the ordinary name still finds the photo.
PLACE_WORDS = {
    "UT": "Utah",
    "WY": "Wyoming",
    "MT": "Montana",
    "CO": "Colorado",
    "OR": "Oregon",
    "WA": "Washington",
    "TN": "Tennessee",
    "FL": "Florida",
    "IN": "Indiana",
    "IL": "Illinois",
    "MO": "Missouri",
    "NV": "Nevada",
    "NP": "national park",
    "HWY": "highway",
    "HWY1": "highway 1 overseas highway",
    "I-80": "interstate 80",
}


def expand_place(location):
    extra = []
    lowered = location.lower()
    if "yellow stone" in lowered:
        extra.append("yellowstone")
    if "smokey" in lowered:
        extra.append("smoky great smoky mountains")
    if "rocky mtn" in lowered:
        extra.append("rocky mountain")
    if "st louis" in lowered:
        extra.append("saint louis")
    if "salt lake" in lowered:
        extra.append("utah")
    for token in re.split(r"[\s,]+", location):
        extra.append(PLACE_WORDS.get(token, ""))
    return " ".join(part for part in extra if part)


def posts():
    entries = []
    for path in sorted(glob.glob(os.path.join(ROOT, "blogs", "*.html"))):
        name = os.path.basename(path)
        if name == "blogs.html":
            continue

        html = open(path).read()
        title = first(r"<h1>(.*?)</h1>", html) or first(r"<title>(.*?)</title>", html)
        meta = first(r'<p class="post-meta">(.*?)</p>', html)

        body = re.search(r'<div class="post-body">(.*?)</p>', html, re.S)
        snippet = text_of(body.group(1))[:160] if body else ""

        entries.append(
            {
                "title": title,
                "url": "blogs/" + name,
                "group": "Adventures",
                "meta": meta,
                "keywords": " ".join([meta, snippet]),
            }
        )

    # Newest first, matching the order on the blog index.
    return entries


def photos():
    path = os.path.join(ROOT, "photography", "portfolio.html")
    if not os.path.exists(path):
        return []

    html = open(path).read()
    cards = re.findall(
        r'<a\s+class="photo-card"(.*?)</a>', html, re.S
    )

    entries = []
    for position, card in enumerate(cards):
        def attr(name, card=card):
            match = re.search(r'data-%s="([^"]*)"' % name, card)
            return match.group(1) if match else ""

        thumb = re.search(r'src="\.\./images/web/([^"]+)"', card)
        location = attr("location")
        pieces = [attr("date"), attr("camera"), attr("lens"), attr("settings")]

        entries.append(
            {
                "title": location,
                "url": "photography/portfolio.html",
                "group": "Photos",
                "meta": " · ".join([p for p in pieces if p][:2]),
                "keywords": " ".join([location, expand_place(location)] + pieces),
                "photo": position,
                "thumb": "images/web/" + thumb.group(1) if thumb else None,
            }
        )
    return entries


def main():
    index = PAGES + posts() + photos()
    for entry in index:
        if entry.get("thumb") is None:
            entry.pop("thumb", None)

    with open(OUT, "w") as handle:
        handle.write(BANNER)
        handle.write("window.SITE_SEARCH_INDEX = ")
        json.dump(index, handle, indent=1, ensure_ascii=False)
        handle.write(";\n")

    counts = {}
    for entry in index:
        counts[entry["group"]] = counts.get(entry["group"], 0) + 1
    print("wrote %s" % os.path.relpath(OUT, ROOT))
    for group, count in sorted(counts.items()):
        print("  %-12s %d" % (group, count))


if __name__ == "__main__":
    main()
